version: '2'
services:
  web_one:
    build:
      context: ./project_one
      dockerfile: dockerfile_one
    container_name: web_one
    ports:
     - "8001:8001"
    restart: always
  web_two:
    build:
      context: ./project_two
      dockerfile: dockerfile_two
    container_name: web_two
    ports:
     - "8002:8002"
    restart: always
